### ISSUE TITLE
TypeError running limitMaster.py

### ISSUE THREAD

**Issue by nightwallaby** [awslabs/aws-limit-monitor#1]
Hi,

When trying to execute a Test Event I receive the following error:

cannot concatenate 'str' and 'int' objects: TypeError
Traceback (most recent call last):
  File "/var/task/limitMaster.py", line 10, in lambda_handler
    print "do stuff here with AWS account "+id+"
"
TypeError: cannot concatenate 'str' and 'int' objects

Any help would be appreciated.

Cheers,
S

**Comment by lukaf** [comment]
The whole code is a bit of a mess. If you can, change line 17 in limitMaster.py file to:
`print "do stuff here with AWS account " + str(id) + "\n"`

Replace the old limitMaster.py in the ZIP archive and upload it to MasterLambda function.

**Comment by nightwallaby** [comment]
Thank you, that's fixed the error.

**Comment by trobiv** [comment]
Fixed in latest update
