### ISSUE TITLE
Cannot deploy the solution from management account

### ISSUE THREAD

**Issue by tivanov-qb** [awslabs/aws-limit-monitor#102]
Deploying solution via OU:
After initializing the Stack deployment, we are getting error:
Resource handler returned message: “Account used is not a delegated administrator (Service: CloudFormation, Status Code: 400, Request ID: 817baaf0-ce0b-416a-9b0e-1ca95c577ba9)” (RequestToken: 8a915966-66ff-e18c-c3db-2ec3dbcde99f, HandlerErrorCode: InvalidRequest)

We followed the steps in the deployment guide ([https://docs.aws.amazon.com/solutions/latest/quota-monitor-for-aws/deploy-the-solution.html]) and attempted to register our management account as a delegated administrator in order to deploy the solution at the organization level and use it as ‘monitoring account’.
However, we encountered an error when attempting to register the account. The error message was: \"Failed to register account XXXXXXXXXX as a delegated administrator. You cannot register master account/yourself as delegated administrator for your organization.\"
After reviewing the AWS documentation, we found that the management account of the organization cannot be registered as a delegated administrator. Only member accounts can be designated as delegated administrators. This information can be found in the AWS Organizations API Reference ([https://docs.aws.amazon.com/organizations/latest/APIReference/API_RegisterDelegatedAdministrator.html]).
From our understanding, this is an OU feature that should be working from the OU management account.
To conclude, we cannot deploy the solution because management account is not registered as delegated administrator, however it has sufficient permissions as we have multiple stacksets cross multiple accounts and if we try registering the account as delegated administrator, we are getting an error that the management account cannot be registered.

Managed to workaround this error by replacing “CallAs”: “DELEGATED_ADMIN” with “CallAs”: “SELF”, so my hub stack was deployed as CF template. Then, I had to manually add stack instances part of the OU as passing the OU to SSM param requires Delegated Administrator and this is not possible in my case.

Can you please help fixing this ?

Thanks!

**Comment by abe-aws** [comment]
Following the [best practices](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_best-practices_mgmt-acct.html), the solution doesn't deploy stacks in the management account.

**Comment by T1ckL35** [comment]
Just noting that this caught me out today whilst trying to deploy the solution to two accounts (management one and a spoke one).
Finally found it mentioned in this ticket so that I knew to add a third account in the mix to take the role of the delegated admin account.

I think it would really help if you pointed this out in the readme to stop other people stumbling around and missing it.
