### ISSUE TITLE
Slack message mapping of values is wrong

### ISSUE THREAD

**Issue by ishahid** [awslabs/aws-limit-monitor#13]
<img width="471" alt="screen shot 2018-07-18 at 9 16 16 am" src="https://user-images.githubusercontent.com/149186/42850513-5beb9a02-8a6b-11e8-84eb-53f03a17f2bd.png">

As shown in the screenshot above the values under LimitName, CurrentUsage and LimitAmount is wrong.

**Comment by shsenior** [comment]
Addressed with v5.1
