### ISSUE TITLE
Unable to get test notifications to the Slack when the  "Slack Notification Level" parameter was set to "OK" state

### ISSUE THREAD

**Issue by bhavanik03** [awslabs/aws-limit-monitor#19]
By default we receive test notifications only when  “WARN” or “ERROR” state is reached. So to get notifications I set the value to "OK" and still I was not able to get the notifications

**Comment by gsingh04** [comment]
What I understand from your comment, is you are receiving slack notifications but when you change it to "OK", you don't get the notifications? Is my understanding correct?
Also, note that there are 2 separate parameters for email/slack notifications. If you are referring to slack notifications, please make sure your adjust the appropriate parameter **Slack Notification Level** to "OK".
