### ISSUE TITLE
Add new service limit checks added 01/18/2019

### ISSUE THREAD

**Issue by albuch** [awslabs/aws-limit-monitor#21]
New service limit checks were added in January 2019 for Route53 and DynamoDB: https://aws.amazon.com/about-aws/whats-new/2019/01/aws-trusted-advisor-expands-functionality/

**Comment by gsingh04** [comment]
We have added your request to our solution backlog items and it will be considered in future
solution releases. We thank you for your contribution.

**Comment by gsingh04** [comment]
The fix has been pushed with release v5.2. We thank you for your contribution.
