### ISSUE TITLE
Create Trust Is Failing - PolicyLengthExceededException

### ISSUE THREAD

**Issue by asantos-fuze** [awslabs/aws-limit-monitor#26]
Hi,

When deploying the AWS Limit Monitor to 30+ accounts, we are getting this error on the Lambda Function LimtrHelperFunction, that support the CFn Custom Resource.
```json
{
    "CreateTrust": {
        "status": "ERROR",
        "account": "xxxxxxxxxxxx",
        "response": {
            "message": "Policy size would be larger than the maximum allowed.",
            "code": "PolicyLengthExceededException",
            "time": "2019-xx-xxTxx:xx:xx.263Z",
            "requestId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
            "statusCode": 400,
            "retryable": false,
            "retryDelay": 89.38078875757718
        }
    }
}
``` 
From what I could find out this is happening because we are reaching the limit of 10KB for the permission policy of the event bus.

From the python SDK [1] (I believe on nodejs is the same) I've read the following:

> if all the accounts are members of the same AWS organization, you can run PutPermission once specifying Principal as "*" and specifying the AWS organization ID in Condition , to grant permissions to all accounts in that organization

So, is it possible to update the CFn templates and CFn Lambda Helper functions to support using the AWS Org ID in the `createTrust` function?

[1] - https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/events.html#CloudWatchEvents.Client.put_permission

**Comment by gsingh04** [comment]
Thanks for reporting this issue with the solution. We have added it to our backlog items and it will be considered in next solution releases.

**Comment by gsingh04** [comment]
Please review instruction here: https://github.com/awslabs/aws-limit-monitor/issues/44#issuecomment-614543908

**Comment by snowake4me** [comment]
@gsingh04 In our shop, we tried the instructions from Issue #44 -- but (as noted there) the spoke stack still fails indicating that it cannot communicate with the centralized Event Bus.  Just wondering if there's some 'conflict' between the account-specific and org-level permissions?  Guess we could try removing the account-specific permissions and see what happens.  Will report back (on Issue #44).  Thanks again!

**Comment by gsingh04** [comment]
Closing this thread, please keep communication related to #44 on that specific thread. Backlog item has already been created to support organization id out of the box with the solution for future release
