### ISSUE TITLE
SSM Parameter name must be a fully qualified name

### ISSUE THREAD

**Issue by morufevari** [awslabs/aws-limit-monitor#28]
## Version
5.2

## Issue
When a slack notification is enabled with the values:
```
SlackChannel: service-limit-alerts
SlackHookURL: https://hooks.slack.com/services/xxxxxx/xxx/xxx
```
The following error is logged in CloudWatch:
```
{
    "SSMParameter": {
        "channelKey": "service-limit-alerts",
        "hookKey": "https://hooks.slack.com/services/xxxxxx/xxx/xxx",
        "response": {
            "message": "Parameter name must be a fully qualified name.",
            "code": "ValidationException",
            "time": "2019-08-08T12:05:04.216Z",
            "requestId": "07cae9a5-1a44-4090-a361-7d070cf7f151",
            "statusCode": 400,
            "retryable": false,
            "retryDelay": 94.35200443904534
        }
    }
}
```

## Investigation
`LimtrHelperFunction -> lib/index.js` revealed the SSM parameter value by default is `SLACK_DUMMY`:
```
await Promise.all(
      data.InvalidParameters.map(async ssmParam => {
        console.log(ssmParam);
        await ssm
          .putParameter({
            Name: ssmParam /* required */,
            Type: 'String' /* required */,
            Value: 'SLACK_DUMMY' /* required */,
          })
          .promise();
      })
    );
```

Also, there is this block of code in `SlackNotifier -> lib/slack-notify.js`:
```
self.ssm.getParameter(
            {
              Name: _self.slackHookURL,
              WithDecryption: true,
            },
            function(err, _hookData) {
              if (err) return cb(err, null);
                 LOGGER.log('ERROR', err.stack);
                 return cb(err, null); // an error occurred;
              } else {
                  let _slackURL = _hookData.Parameter.Value;

                   let _slackMssg = _self.slackMessageBuilder(event);
                   _slackMssg.channel = _channelData.Parameter.Value;
              ...
           }
```
This obviously means whatever value is retrieved from `SlackChannel` and `SlackHookURL` are what would be used to try to send a message to Slack; in both cases `SLACK_DUMMY` would be returned by `SSM`.

## Potential Solution
I think what needs to be done is to allow `SlackChannel`, `SlackHookURL` and their corresponding SSM keys `SlackChannelKey`, `SlackHookURLKey` to be specified as [SSMParameters -> Properties](https://github.com/awslabs/aws-limit-monitor/blob/master/deployment/limit-monitor.template#L559). And then stored as name and value pairs in `SSM`.

Happy to work on a fix, if you want!

**Comment by gsingh04** [comment]
Thanks for your question. We take input of Slack Channel **Key** and Slack Hook URL **Key** as part of the parameters in the template. We **do not** expect customers to provide **Values** as this is not a good practice from security standpoint. We expect customers to update the SSM parameters with the actual values for slack integration. Solution creates it with DUMMY values.
Additionally, the solution would not create Slack SSM parameters if the mentioned parameters already exist in the account.

Expected steps:
1. Deploy the template with Slack Channel and Slack Hook URL Key
let's say mySlackChannel and mySlackURL
2. This will create **mySlackChannel** and **mySlackURL** SSM parameter
3. Go to SSM Parameter and update the above parameters with actual values
let's say
mySlackChannel: service-limit-alerts
mySlackURL: https://hooks.slack.com/services/xxxxxx/xxx/xxx

See troubleshooting section [Slack Notifications Are Not Being Received](https://docs.aws.amazon.com/solutions/latest/limit-monitor/appendix-a.html)

**Comment by morufevari** [comment]
Thank you for taking the time to respond to this. It's not actually an issue just have you addressed.

After using fully qualified names for the SSM parameters and updating the values in the console, everything is working as expected now.

**Comment by puramashok2013** [comment]
_After using fully qualified names for the SSM parameters and updating the values in the console, everything is working as expected now._

Please let me know what parameter key value pairs you have used

**Comment by lysterious** [comment]
Also wondering what the correct values are. 

Not sure what is meant by with the last step in instructions above by @gsingh04:

> 1. Deploy the template with Slack Channel and Slack Hook URL Key, let's say **mySlackChannel** and **mySlackURL**
> 2. This will create **mySlackChannel** and **mySlackURL** SSM parameter
> 3. Go to SSM Parameter and update the above parameters with actual values, let's say
>     mySlackChannel: service-limit-alerts
>     mySlackURL: https://hooks.slack.com/services/xxxxxx/xxx/xxx

How I read the instructions, mySlackChannel **IS** service-limit-alerts. What **key** does it have? What should we look for in the SSM Parameter?
