### ISSUE TITLE
The Limits Report is not accurate

### ISSUE THREAD

**Issue by RongQiao** [awslabs/aws-limit-monitor#3]
Hello, I have two problems with using this tool to monitor our enterprise AWS account.
1. The VPC Elastic IP addresses (EIPs) limit
It was reported reaching the 80%(4/5) on 08/26, and the limit was increased to 6 on 08/27. But the monitoring still report below message during 08/28 to 08/29(today). Something wrong with this check. We had other two limits reported and they don't have same problem after the limits were increased.
VPC Elastic IP addresses (EIPs)
Region: us-east-1
Resource Limit: 5
Resource Usage: 4
2. Totally there are 92 limits info reported from trusted advisor under our AWS account, it looks only a few of them are covered by this aws-limit-monitor, and we do have 3 limits already alerted from Trusted Advisor but was not reported by aws-limit-monitor. Can I have idea about what limits this tool covers?

Thanks.

**Comment by trobiv** [comment]
1. This has been resolved in the latest release by manually refreshing the Trusted Advisor alerts using the RefreshTrustedAdvisorCheck API call.

2. The updated solution covers all limits from Trusted Advisor described here (https://aws.amazon.com/premiumsupport/ta-faqs/), maximum instances from the EC2 describe_account_attributes API call, CloudFormation stack limits from the CloudFormation list_stacks API call, and DynamoDB limits from the DynamoDB describe_limits call.  If you have a limit not being reported by the updated tool please reach out with which one and we will test further.
