### ISSUE TITLE
Node.js 8.10 is EOL at the end of 2019, please migrate your Lambda functions to a newer runtime version

### ISSUE THREAD

**Issue by cougar2009** [awslabs/aws-limit-monitor#31]
Wondering what version of Node this will be using going forward with the EOL coming up soon.

**Comment by beomseoklee** [comment]
Thanks for contacting us, and we are planning to update Node.JS version in this year.

**Comment by benvolioT** [comment]
Are you able to provide a more specific timeline?

**Comment by dscpinheiro** [comment]
Hi @benvolioT,

Unfortunately we cannot provide a specific date, but as @beomseoklee mentioned, we plan to update the solution before Node8 reaches its EOL.

**Comment by benvolioT** [comment]
Hi @dscpinheiro and @beomseoklee  - Any update? I believe the EOL date is January 1, 2020, and with the Christmas holiday approaching, there isn't much time left to get the updated solution rolled out. Please let us know if we can still expect this soon.

**Comment by knihit** [comment]
Hi @benvolioT, we released a new version couple of days back that includes the new Node runtime. Please review and let us know.

**Comment by davidclin** [comment]
I was able to successfully deploy the new version today, and it's working as intended.
Thank you for the quick turnaround.
