### ISSUE TITLE
Connection refused - Slack Notification

### ISSUE THREAD

**Issue by rafaelsilvaa10** [awslabs/aws-limit-monitor#32]
Hello, I am getting

```
2019-11-05T02:21:27.912Z c58f1545-4b3d-457a-ab90-4ac3f5206fa3 Error: connect ECONNREFUSED 127.0.0.1:443
at Object._errnoException (util.js:1022:11)
at _exceptionWithHostPort (util.js:1044:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
```

 error in lambda slack notification, I only find this error in the logs.

I get the email correctly, but slack notifications don't work.

I used the oficial documentation https://aws.amazon.com/solutions/limit-monitor/

someone experiencing the same problem?
thanks

**Comment by dscpinheiro** [comment]
Hi @rafaelsilvaa10,

Sorry for the delay in the response.

Is this error happening consistently? If so, could you check the SSM parameters were created successfully? Even though the stack might be in a _CREATE_COMPLETE_ status, it might have failed (as explained in https://github.com/awslabs/aws-limit-monitor/issues/30#issuecomment-541181494), so you'd need to check the CloudWatch logs.

**Comment by georgebearden** [comment]
Hi @rafaelsilvaa10 - Closing this issue for now, but please let us know if you need additional assistance. Thank you.
