### ISSUE TITLE
Typo in template file causing failure to deploy

### ISSUE THREAD

**Issue by qayshp** [awslabs/aws-limit-monitor#36]
Error when using template in master and on S3.

> Cannot render the template because of an error.: YAMLException: duplicated mapping key at line 334, column 30: Effect: Allow ^

Caused by: 
https://github.com/awslabs/aws-limit-monitor/commit/3d71c27946ca8fec4b40231e4d0a43365f2a67f6#diff-9b113a30da49f7487f0c44f9f6556492R334

**Comment by qayshp** [comment]
If anyone has a chance to review, this can be closed after merging #37 and updating the template in s3 https://s3.amazonaws.com/solutions-reference/limit-monitor/latest/limit-monitor.template
After looking at past closed PRs, it looks like perhaps @gsingh04 or @knihit do this, and the gold copy of the code lives outside of github, perhaps internally on gitfarm.

**Comment by georgebearden** [comment]
Hi - This should have been resolved in the most recent commit to this Solution. Please let us know if you need additional assistance.
