### ISSUE TITLE
CloudWatch event(SQSRule) invocation failed.

### ISSUE THREAD

**Issue by kenmick** [awslabs/aws-limit-monitor#38]
CloudWatch event(SQSRule) invocation failed when trying to send message to SQS. Seems SQS uses an AWS managed key `alias/aws/sqs` for encryption. https://github.com/awslabs/aws-limit-monitor/blob/master/deployment/limit-monitor.template#L225
However, this key is not accessible for CloudWatch event due to the following limit defined in the key policy.
```
"Condition": {
    "StringEquals": {
        "kms:CallerAccount": "xxxxxxxxxxxxxxx",
        "kms:ViaService": "sqs.us-east-1.amazonaws.com"
    }
}
```
I suppose that a customer managed key should be used here just like SNS part. https://github.com/awslabs/aws-limit-monitor/blob/master/deployment/limit-monitor.template#L471

**Comment by georgebearden** [comment]
Hi - This should have been resolved in the most recent commit to this Solution. Please let us know if you need additional assistance.
