### ISSUE TITLE
Monitor is alerting labelling excluded Service Limits from TrustedAdvisor as Warnings

### ISSUE THREAD

**Issue by rchenzheng** [awslabs/aws-limit-monitor#40]
```
@aws-limit-monitor
Limit Monitor Documentation
AccountId
XXXXXXXXXXXXXX
Status
:warning:
TimeStamp
2020-01-21T20:00:15Z
Region
us-east-1
Service
RDS
LimitName
Max auths per security group
CurrentUsage
20
LimitAmount
20
```

It seems that even though the service limit has been excluded from the TA service limit check, the alert is still being sent as a warning. As you may know. RDS's "Max auths per security group" is a hard limit

**Comment by gsingh04** [comment]
Can you please confirm you removed 'dBkuNCvqn5' from RDS service limit checks here:
https://github.com/awslabs/aws-limit-monitor/blob/1f365564eae725aeac994bbbd5b2895d76c30332/source/services/tarefresh/lib/ta-refresh.js#L66
Once you update this list, the solution shouldn't be refreshing this particular check. However, if you visit TA Console or refresh TA checks through any other mechanism outside the solution, it might still refresh that check and send you the alert. You can also enable debug mode on the solution to see if that particular check is being refreshed by the solution or not. Turn LOG_LEVEL to DEBUG
https://github.com/awslabs/aws-limit-monitor/blob/1f365564eae725aeac994bbbd5b2895d76c30332/deployment/limit-monitor-spoke.template#L165
Reference [here](https://docs.aws.amazon.com/solutions/latest/limit-monitor/appendix-a.html)
