### ISSUE TITLE
Deployment not working - failing cloudwatch events

### ISSUE THREAD

**Issue by ryan-dyer-sp** [awslabs/aws-limit-monitor#41]
I have deployed the stack, but dont believe it is working as expected.  

I enabled DEBUG on all the lambdas and I see in the limitCheckStack only the following message:
START RequestId: b3f11639-74d7-439e-9751-896b78fa6c48 Version: $LATEST
18:55:17
2020-02-06T18:55:17.338Z b3f11639-74d7-439e-9751-896b78fa6c48 INFO [ERROR]UnknownEndpoint: Inaccessible host: `servicequotas.eu-north-1.amazonaws.com'. This service may not be available in the `eu-north-1' region.
18:56:09
END RequestId: b3f11639-74d7-439e-9751-896b78fa6c48

There is nothing in the dynamodb table and nothing being sent to either of the SQS.  The Troubleshooting section suggests ensuring that the account ID is correct.  I have verified the account is correct and "surrounded".

I see from the Lambda > Application > Monitoring > CW Events that all of the cw events have "Failed Invocations".  No other monitoring tabs show any errors.

Please assist.

Thanks,
Ryan

**Comment by ryan-dyer-sp** [comment]
I found issue #38 and applied the PR associated with it (customer managed KMS key).  I am now getting events into SQS but still not seeing anything in the DynamoDB table.  The SQS queue is perpetually receiving events, but nothing appears to be taking them off the queue.

**Comment by ryan-dyer-sp** [comment]
From LimitMonitorSummarizer
```
2020-02-07T14:15:13.821Z	6bbcc889-e0e9-4211-aaa2-441275899b1d	INFO	[ERROR]
{
    "TableUpdate": {
        "status": {
            "message": "User: arn:aws:sts::641575277437:assumed-role/LimitMonitor-LimitSummarizerRole-P3EDOFPEKRQL/LimitMonitor-LimitSummarizer-1BDQRO0OIK09E is not authorized to perform: dynamodb:PutItem on resource: arn:aws:dynamodb:us-east-1:641575277437:table/LimitMonitor-SummaryDDB-6WGN94OQHFIA",
            "code": "AccessDeniedException",
            "time": "2020-02-07T14:15:13.820Z",
            "requestId": "E8929Q07U0O6K1QH76S19EEHE7VV4KQNSO5AEMVJF66Q9ASUAAJG",
            "statusCode": 400,
            "retryable": false,
            "retryDelay": 14.54961769739902
        }
    }
}
```

**Comment by ryan-dyer-sp** [comment]
PR #39 and PR #42 fix this issue.

**Comment by gsingh04** [comment]
this has been addressed with latest release, we appreciate you bringing this to our attention
