### ISSUE TITLE
AccountList Parameter Value Limit

### ISSUE THREAD

**Issue by jonjohnston** [awslabs/aws-limit-monitor#44]
With over 100+ accounts loaded in the accountlist, I am hitting the parameter value limit for this. Solution is to have 2-3 parameter lists and doing a join

**Comment by gsingh04** [comment]
Are the accounts part of AWS Organizations? If that is the case then I request you to follow given steps to overcome this limitation while we also look to make this part of automated deployment:
1. Go to CloudWatch console, [here](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#eventbuses:)
2. Click on **Add permission**
3. Chose Type **Organization**
4. Enter value for **Organization ID**
This should allow **all** accounts in the given Organization permission to send events to the bus. Reference [link](https://docs.aws.amazon.com/eventbridge/latest/userguide/create-event-bus.html)

**Comment by snowake4me** [comment]
Thanks for the #ProTip on Organization-level permissions to the event bus.  We also have > 120 accounts, and were not looking forward to adding, and maintaining, a discrete list of account numbers.

**Comment by snowake4me** [comment]
Greetings, @gsingh04 !  I attempted to implement the AWS Organization level permission as you suggested above -- but alas, when attempting to deploy the Spoke Template to another account within our organization, the template fails and rolls back, with the following error:

Access to the resource arn:aws:events:us-east-1:<account number>:event-bus/default is denied. Reason: EventBus does not exist or its policy does not allow this operation. (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: AccessDeniedException; Request ID: 93c13145-51ad-46ac-94c1-9d599ade2adf)

I'm confident I'm deploying in the same region (us-east-1) where the primary template is deployed in the centralized account.  Permissions on the event bus look like this:

![image](https://user-images.githubusercontent.com/12039766/87736957-7f1b4b00-c78e-11ea-913d-2c9c7c95046a.png)

Do we need to first _remove_ the account-specific permissions prior to adding the Organization-level ones?  I wouldn't think so - but then not sure why it's not working?

**Comment by snowake4me** [comment]
@gsingh04 Thanks for the update on this issue.  We're looking to deploy across 120+ (and growing) accounts -- and really want to leverage the AWS Organization level permissions.  I tried adding, as noted above - and it still didn't work, until I explicitly added the account number.

Question:  Do we need to **remove** the account-specific permissions, lest they 'interfere' with the organization-level permissions?  I wouldn't think so - but surprised when it didn't work.

Thanks!

**Comment by gsingh04** [comment]
Hello,

That should not be the case. However, if you have added your organization id to the permission, that should give all member accounts permission to put events on the event bus and you may remove individual account-ids from the permission. I would recommend to try this as well. Also, make sure there are no Organization Service Control Policies restricting your member accounts to publish events to the master account event bus.

**Comment by snowake4me** [comment]
Thanks for the update, Garvit.  I don't believe there are any SCPs in place - we've certainly been able to communicate from 'spoke accounts' to the centralized account no problem, by adding the discrete account number as noted in the Solution.  However,  even after adding the Organization-level permissions - additional accounts are receiving the error shown above.

I'll go back and double / triple-check our work, try another account, etc.  I guess I can also 'experiment' with ripping out the account-specific permissions (delete the accounts from the Parameter Store value) but was hoping not to have to do that (as it will break the accounts we **do** have working) if it's not a known requirement.

Will report back results.  Thanks for your assistance!

**Comment by gsingh04** [comment]
@snowake4me are you still seeing the issue? If the issue has resolved, we would love to hear what helped you.

**Comment by maykays** [comment]
Closing this issue. Please re-open if the problem persists.
