### ISSUE TITLE
Not getting the notification after my sns topic reached there limit

### ISSUE THREAD

**Issue by sandip750** [awslabs/aws-limit-monitor#45]
Hi,
I setup the aws limit checker for my aws account but when our sns topic limit reached,
I don't get any email from this.
What is the issue here, I am missing something or there is some bug with the code 

 (ap-southeast-1)
If you need more details I can share wtih you

**Comment by gsingh04** [comment]
Hello,

The solution leverages Trusted Advisor checks. For list of supported service limit checks please read [here](https://aws.amazon.com/premiumsupport/ta-faqs/#service-limits-check-questions).

As you can see SNS is currently not supported on TA service limit checks.

**Comment by sandip750** [comment]
Thanks
