### ISSUE TITLE
"VPC" Trusted Advisor limit is being labeled as "Network Interfaces" in SNS notification

### ISSUE THREAD

**Issue by benvolioT** [awslabs/aws-limit-monitor#46]
It looks as though a Trusted Advisor limit that is labeled as "VPC" in the TA UI is instead named "Network Interfaces" in the SNS notification. 
![Screen Shot 2020-05-14 at 5 14 37 PM](https://user-images.githubusercontent.com/1524167/81992617-7e88fb80-9609-11ea-9e52-b78d7967de98.png)
![Screen Shot 2020-05-14 at 5 26 17 PM](https://user-images.githubusercontent.com/1524167/81992736-d45da380-9609-11ea-88a8-3e60fffec726.png)

**Comment by deolank** [comment]
The solution does not change the limit names published from Trusted Advisor. If you still see this issue, this would be an issue with the service Trusted Advisor.
