### ISSUE TITLE
use managed policies vs inline

### ISSUE THREAD

**Issue by epequeno** [awslabs/aws-limit-monitor#48]
We've deployed this solution and we're now getting notifications from best practices checks about the inline policy used by this solution:
https://github.com/awslabs/aws-limit-monitor/blob/1f365564eae725aeac994bbbd5b2895d76c30332/deployment/service-quotas-checks.template#L57-L75

Would it be possible to change this from an inline policy to a managed policy?

Supporting docs:
> The different types of policies are for different use cases. In most cases, we recommend that you use managed policies instead of inline policies. 
https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_managed-vs-inline.html

> For custom policies, we recommend that you use managed policies instead of inline policies.
https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#best-practice-managed-vs-inline

**Comment by gsingh04** [comment]
Hello,

Thanks for your feedback.

Managed policies would be more open from permission standpoint and hence we want to restrict permissions to least access privilege.
