### ISSUE TITLE
deploy to different region?

### ISSUE THREAD

**Issue by SpyderDave** [awslabs/aws-limit-monitor#50]
Has anyone successfully deployed this solution to a different region?

**Comment by rakshb** [comment]
Hello @SpyderDave The CFN template will rollback if you deploy it in any other region other than us-east-1. 

Thanks,
Rakshana

**Comment by gsingh04** [comment]
The solution doesn't need to be deployed in any other region. Limit Monitor leverages AWS Trusted Advisor and Trusted Advisor uses us-east-1 as its data plane. You just need to deploy in us-east-1 and it will monitor all regions.

Please feel free to open the ticket again, if there are more questions.
