### ISSUE TITLE
Lambda Servicequotas Permission Issue

### ISSUE THREAD

**Issue by dysnomea** [awslabs/aws-limit-monitor#51]
New spoke deploy. 

INFO	[ERROR]AccessDeniedException: User: arn:aws:sts::[account id]:assumed-role/limit-monitor-limitCheckStack-GQH-LimitMonitorRole-1HLZ084R28ABB/limit-monitor-limitCheckStack-LimitMonitorFunction-ENB26B3ETQB8 is not authorized to perform: servicequotas:GetAWSDefaultServiceQuota with an explicit deny

IAM role attached to Lambda function has servicequotas:GetAWSDefaultServiceQuota for all resources so I don't understand why it's getting an explicit deny.

**Comment by snowake4me** [comment]
+1

We're seeing this same error - and are wondering if, in our case, it's because there are certain AWS regions that we're unable to communicate with?  That seems unlikely though, as the error in the logs makes it quite clear that it's a 'permission denied' error.

**Comment by dysnomea** [comment]
interesting. i have a service control policy to deny accessing any AWS resource that's not in the USA. so my accounts are in a similar boat with having regions that are unable to communicate, which in my case would return an explicit deny. i didn't even think of that.

**Comment by gsingh04** [comment]
Hello,

Can you please confirm if the Organization service control policies in place are resulting this behavior? The SCP will trump IAM policies so that might be the case. We look forward to hearing from you.

**Comment by snowake4me** [comment]
In our case, we have a combination:  Both a Service Control Policy applied at the AWS Organization level -- as well as a technical implementation in our firewalls that are blocking (actually 'dropping') all communications to a list of discrete countries.  Any value in providing the error messages we're seeing, here?

**Comment by snowake4me** [comment]
Here's an example.  Each time the limitCheckStack function runs, we receive exactly 12 instances of the following error:

`2020-07-21T02:06:21.287Z	9ddd7b04-738a-4d85-bb44-605b08d72861	INFO	[ERROR]AccessDeniedException: User: arn:aws:sts::<account number>:assumed-role/limit-monitor-limitCheckStack-9TD-LimitMonitorRole-WXKGEL148YJR/limit-monitor-limitCheckStack-LimitMonitorFunction-1L0KPSH1XGUB5 is not authorized to perform: servicequotas:GetAWSDefaultServiceQuota with an explicit deny`

Seems pretty straight-forward, right?  Except, looking at the execution role created for this Lambda, is seems it **does** have permission, per this excerpt from the inline policy:

`        {
            "Action": [
                "servicequotas:GetServiceQuota",
                "servicequotas:GetAWSDefaultServiceQuota",
                "servicequotas:ListServiceQuotas",
                "cloudwatch:GetMetricData",
                "events:PutEvents",
                "ec2:DescribeRegions"
            ],
            "Resource": "*",
            "Effect": "Allow"
        }`

So it sure seems like we've got an overriding SCP, or even IAM policy (though, while we have many of both -  I can identify neither which should impact the ability of this Lambda to invoke that API).

Strange...
#EternalN00b

**Comment by gsingh04** [comment]
Sorry for the delay in response here. 

I think the problem is arising from below line of source code. If you guys have explicit deny rules to drop traffic for other regions, then essentially the service quote APIs would fail. If you inspect below line of code, you would see it is trying to create regional service quote service client to get default quotas from that region.
https://github.com/awslabs/aws-limit-monitor/blob/1f365564eae725aeac994bbbd5b2895d76c30332/source/services/servicequotaschecks/lib/service-quotas-checks.js#L46

12 instances of error should justify 12 regions where the API calls failed.
