### ISSUE TITLE
Spoke Template has Hard-Coded References to US-East-1 Region

### ISSUE THREAD

**Issue by snowake4me** [awslabs/aws-limit-monitor#52]
Team AWS / Limit Monitor Solution-

First and foremost - thanks for this helpful tool / solution.  We have multiple internal partners in our enterprise who are keenly interested in this service (and more).

We struggled a bit with the deployment - and along the way, found some hard-coded references in the Spoke Template which assume that the centralized (main template) resources in the Primary account are deployed in us-east-1.  At first, we simply  updated these references to point to us-west-2, where we had Deployed the primary stack in a centralized account.  When things didn't work, we cut bait, went back to the 'stock' templates provided in the Solution, and deployed everything in us-east-1.

Happy to submit a PR to address this hard-coded dependency - by either allowing the user to 'select' the region for the centralized / 'back-end' services -- or my changing the hard-coded references to intrinsic functions and just looking for those resources in the same region in which the spoke template is executed.

Thanks again for this Solution!  We hope to use it as a foundation, incorporating additional limit monitoring not currently provided by Trusted Advisor, but feeding into the same collection / notification / archiving back-end - and will be sure to offer any enhancements developed back to the solution in the form of a PR.

**Comment by gsingh04** [comment]
Hello,

Thanks for the valuable feedback. I would like to tell you that the solution essentially leverages AWS Trusted Advisor service limit checks. The TA checks uses us-east-1 as its data plane, implying you need to deploy the solution and spoke template in us-east-1 only. It will not work in any other region. That being said, it will monitor **ALL** regions even though it only allows us-east-1 deployment. Hope it helps. Please feel free to come back anytime should you have more questions.

**Comment by snowake4me** [comment]
@gsingh04 Outstanding!  Thanks for this confirmation / clarification.  It could be that this is clearly articulated within the Solution Deployment Guide - but we had four sets of eyes on it as we stood it up, and didn't come across that (totally makes sense) guidance / caveat.  Totally understand that the TA service reports across all regions.  Closing out this issue -- thanks again for the great work on this product!
