### ISSUE TITLE
Check Deprecation Warning

### ISSUE THREAD

**Issue by TheBrigandier** [awslabs/aws-limit-monitor#57]
Hello,

We received a warning from AWS that the following checks are now deprecated and scheduled to be removed on Nov 18th:

>This notification will impact you if you are using one of the following checks in AWS Trusted Advisor:
>
> 1. EC2Config Service for EC2 Windows Instances in Fault Tolerance category with Check ID V77iOLlBqz
> 2. PV Driver Version for EC2 Windows Instances in Fault Tolerance category with Check ID Wnwm9Il5bG
> 3. NVMe Driver Version for EC2 Windows Instances in Fault Tolerance category with Check ID yHAGQJV9K5
> 4. ENA Driver Version for EC2 Windows Instances in Fault Tolerance category with Check ID TyfdMXG69d
> 5. EBS Active Volumes in Service Limits category with Check ID fH7LL0l7J9
> 
> What is the change?
> 
> AWS Trusted Advisor will remove 5 checks on November 18, 2020. On this date, 5 checks listed above will be removed from the list of checks in both Support API and the Trusted Advisor console. If you consume results from all checks in Trusted Advisor, these checks will not show up in check results. If you specifically consume any of the 5 checks listed above (such as by hard coding the Check ID in an API call), you will need to remove these checks from your list to avoid API call errors.

We see in the current iteration of `aws-limit-monitor` that the EBS Active Volumes check seems to be used: https://github.com/awslabs/aws-limit-monitor/blob/master/source/services/tarefresh/lib/ta-refresh.js#L38 - there may be others, this is just the first I spotted.

Are there any plans to update this tool so the above check deprecation doesn't cause breakage?

Thanks!

**Comment by gsingh04** [comment]
Thanks for bringing this to our attention.

We will continue to maintain and update the solution to ensure the Trusted Advisor updates doesn't break the solution. We have added the issue to our backlog to be addressed in next release.

**Comment by rakshb** [comment]
@TheBrigandier Hello. Garvit and our team did initial validation on this warning. You can continue to use the solution even if TA service deprecates those 5 checks since the solution is designed to handle the related API calls accordingly. Meanwhile, we will address the issue in our next release
