### ISSUE TITLE
Cloudformation Failing TARefresher

### ISSUE THREAD

**Issue by jonjohnston** [awslabs/aws-limit-monitor#58]
Seems the limit-monitor-spoke template is now failing because it is creating a function called TARefresher instead of {stackname}-TARefresher-{randomcharacters}

This is preventing me from creating multiple stacks in the same account

**Comment by gockle** [comment]
Hi @jonjohnston We are sorry about the issue, we are working to rectify the template, will notify here once the changes are tested and available.

**Comment by gockle** [comment]
Hi @jonjohnston We have updated the limit-monitor-spoke template, and we have tested it for multiple deployments in the same account. Let us know if you still face any issue. 

* Link to template: [LimitMonitorSpoke.template](https://s3.amazonaws.com/solutions-reference/limit-monitor/latest/limit-monitor-spoke.template)
