### ISSUE TITLE
where will I get 'initialize-repo.sh script?'

### ISSUE THREAD

**Issue by DipankarChakrabartiTR** [awslabs/aws-limit-monitor#66]
Hi 
I am planning to  run the    'build-s3-dist.sh'    from the deployment  directory.  I have noted that the 1st prerequisite is :
Important notes and prereq's:
#   1. The initialize-repo.sh script must have been run in order for this script to
#      function properly.

Can anyone please  advise me where  I could get this above mentioned 'initialize-repo.sh script?'

Dipankar Chakrabarti

**Comment by gockle** [comment]
@DipankarChakrabartiTR You can run the build-s3-dist.sh script without the intialize-repo.sh, it  is referring to a file which is not part of this repository, We will update the comments in the file to remove any references to initialize-repo.sh, Meanwhile let me know if you face any issue using the build-s3-dist.sh.
