### ISSUE TITLE
Due to updates to IAM permissions in EventBridge, existing instructions about adding permissions don't work

### ISSUE THREAD

**Issue by coderbec** [awslabs/aws-limit-monitor#67]
I am trying to work out the full policy to manually put in to avoid the issue "Amazon CloudWatch Events Bus Permissions Error". The instructions in the troubleshooter are no longer correct. 

Firstly we can't add them anymore in cloudwatch console we have to add them in EventBridge, secondly adding the permissions fro the root/master account alone doesn't work fully, I think I have to do something in the sending account as well as the receiving account. 

I am adding something similar in receiving/master account: 

"Version": "2012-10-17",
  "Statement": [{
    "Sid": "limtr-458054464678",
    "Effect": "Allow",
    "Principal": {
      "AWS": "arn:aws:iam::<ID of master/receiver account with event bus in it>:root"
    },
    "Action": "events:PutEvents",
    "Resource": "arn:aws:events:us-east-1:<ID of master/receiver account with event bus in it>:event-bus/default"
  }, {
    "Sid": "842046a0-70a3-11eb-95a7-93a72639c6a91613513316362",
    "Effect": "Allow",
    "Principal": {
      "AWS": "arn:aws:iam::<ID of secondary/sender account>:root"
    },
    "Action": "events:*",
    "Resource": "arn:aws:events:us-east-1:<ID of master/receiver account with event bus in it>:event-bus/default"
  }]
}

**Comment by gsingh04** [comment]
Hello,

Can you try with following permission snippet:

```
 {
    "Sid": "limtr-1010",
    "Effect": "Allow",
    "Principal": {
      "AWS": "<ID of secondary/sender account>"
    },
    "Action": "events:PutEvents",
    "Resource": "arn:aws:events:us-east-1:<ID of master/receiver account with event bus in it>:event-bus/default"
  }
```
The same permission can be seen here:
https://github.com/awslabs/aws-limit-monitor/blob/2afdb45fc215852eaa2a186275c2c6349fca3c09/source/lambda/services/customhelper/lib/index.js#L372

Please feel free to close the thread, if this addressed your question.
