### ISSUE TITLE
Trusted Advisor no longer supports "fH7LL0l7J9" and "aW9HH0l8J6" service checks

### ISSUE THREAD

**Issue by Naga-Abhilash** [awslabs/aws-limit-monitor#73]
When I try to implement the solution with a business support plan, I got the following error: 

"[DEBUG]TA checkId could not be refreshed: fH7LL0l7J9 InvalidParameterValueException: Unknown ID: Account requires a Premium Support Plan for access to Trusted Advisor check: fH7LL0l7J9"

Later I found that we are checking for two service checks that are deprecated by AWS. Please remove the above two checks in the code.

**Comment by gsingh04** [comment]
Thanks for bringing this up @Naga-Abhilash We have added this to our backlog items for next release.

**Comment by gsingh04** [comment]
this is fixed in v5.3.4
