### ISSUE TITLE
Trusted Advisor refresh always runs

### ISSUE THREAD

**Issue by aalbertson** [awslabs/aws-limit-monitor#8]
It appears that when this lambda executes it "always" runs a trusted advisor update check, which can be problematic when you have an account that's very large. I recommend adding in some validation to help it to determine if it's been updated within X amount of time to make sure it's not just always hitting refresh. 

The results of this are the following error:
`Unable to retrieve Trusted Advisor results. Some data may be from the previous report.`

**Comment by gsingh04** [comment]
we have released updated version of the solution, closing the issue. thanks.
